server:
  port: 1234
spring:
  application:
    name: ssm
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
management:
  security:
    enabled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
